//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPS9266xEvaluationModule.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public ushort pwm1Freq_1 {
            get {
                return ((ushort)(this["pwm1Freq_1"]));
            }
            set {
                this["pwm1Freq_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double pwm1DC_1 {
            get {
                return ((double)(this["pwm1DC_1"]));
            }
            set {
                this["pwm1DC_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double pwm2DC_1 {
            get {
                return ((double)(this["pwm2DC_1"]));
            }
            set {
                this["pwm2DC_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool checkBoxEnable {
            get {
                return ((bool)(this["checkBoxEnable"]));
            }
            set {
                this["checkBoxEnable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool checkBoxVREGEnable {
            get {
                return ((bool)(this["checkBoxVREGEnable"]));
            }
            set {
                this["checkBoxVREGEnable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3.3")]
        public double ioVoltage {
            get {
                return ((double)(this["ioVoltage"]));
            }
            set {
                this["ioVoltage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool checkBoxWrite {
            get {
                return ((bool)(this["checkBoxWrite"]));
            }
            set {
                this["checkBoxWrite"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2000")]
        public ushort spiFreq {
            get {
                return ((ushort)(this["spiFreq"]));
            }
            set {
                this["spiFreq"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool radioButton518 {
            get {
                return ((bool)(this["radioButton518"]));
            }
            set {
                this["radioButton518"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool radioButton682 {
            get {
                return ((bool)(this["radioButton682"]));
            }
            set {
                this["radioButton682"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool radioButtonSingle {
            get {
                return ((bool)(this["radioButtonSingle"]));
            }
            set {
                this["radioButtonSingle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool radioButtonStar {
            get {
                return ((bool)(this["radioButtonStar"]));
            }
            set {
                this["radioButtonStar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool radioButtonDaisy {
            get {
                return ((bool)(this["radioButtonDaisy"]));
            }
            set {
                this["radioButtonDaisy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int comboBoxAddress {
            get {
                return ((int)(this["comboBoxAddress"]));
            }
            set {
                this["comboBoxAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool checkBoxLockFreqs {
            get {
                return ((bool)(this["checkBoxLockFreqs"]));
            }
            set {
                this["checkBoxLockFreqs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public byte comboBoxNumDevices {
            get {
                return ((byte)(this["comboBoxNumDevices"]));
            }
            set {
                this["comboBoxNumDevices"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte comboBoxNumSelectedIndex {
            get {
                return ((byte)(this["comboBoxNumSelectedIndex"]));
            }
            set {
                this["comboBoxNumSelectedIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool setMeUp {
            get {
                return ((bool)(this["setMeUp"]));
            }
            set {
                this["setMeUp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public byte maxDevices {
            get {
                return ((byte)(this["maxDevices"]));
            }
            set {
                this["maxDevices"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool setMeUpHolder {
            get {
                return ((bool)(this["setMeUpHolder"]));
            }
            set {
                this["setMeUpHolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool radioButtonHex {
            get {
                return ((bool)(this["radioButtonHex"]));
            }
            set {
                this["radioButtonHex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int savedTab {
            get {
                return ((int)(this["savedTab"]));
            }
            set {
                this["savedTab"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool checkBoxClkSync {
            get {
                return ((bool)(this["checkBoxClkSync"]));
            }
            set {
                this["checkBoxClkSync"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public string textBoxClkSyncFreq {
            get {
                return ((string)(this["textBoxClkSyncFreq"]));
            }
            set {
                this["textBoxClkSyncFreq"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public string textBoxDutyCycle {
            get {
                return ((string)(this["textBoxDutyCycle"]));
            }
            set {
                this["textBoxDutyCycle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("180")]
        public string textBoxPhase {
            get {
                return ((string)(this["textBoxPhase"]));
            }
            set {
                this["textBoxPhase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool radioButton520 {
            get {
                return ((bool)(this["radioButton520"]));
            }
            set {
                this["radioButton520"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int comboBoxEVM {
            get {
                return ((int)(this["comboBoxEVM"]));
            }
            set {
                this["comboBoxEVM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool checkBoxPhase180_1 {
            get {
                return ((bool)(this["checkBoxPhase180_1"]));
            }
            set {
                this["checkBoxPhase180_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool checkBoxSyncPulses_1 {
            get {
                return ((bool)(this["checkBoxSyncPulses_1"]));
            }
            set {
                this["checkBoxSyncPulses_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool radioButtonPWM1 {
            get {
                return ((bool)(this["radioButtonPWM1"]));
            }
            set {
                this["radioButtonPWM1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool checkBoxPhase180_2 {
            get {
                return ((bool)(this["checkBoxPhase180_2"]));
            }
            set {
                this["checkBoxPhase180_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool checkBoxSyncPulses_2 {
            get {
                return ((bool)(this["checkBoxSyncPulses_2"]));
            }
            set {
                this["checkBoxSyncPulses_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public ushort pwm1Freq_2 {
            get {
                return ((ushort)(this["pwm1Freq_2"]));
            }
            set {
                this["pwm1Freq_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double pwm1DC_2 {
            get {
                return ((double)(this["pwm1DC_2"]));
            }
            set {
                this["pwm1DC_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double pwm2DC_2 {
            get {
                return ((double)(this["pwm2DC_2"]));
            }
            set {
                this["pwm2DC_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte userSelectedEVM {
            get {
                return ((byte)(this["userSelectedEVM"]));
            }
            set {
                this["userSelectedEVM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int currentCommand {
            get {
                return ((int)(this["currentCommand"]));
            }
            set {
                this["currentCommand"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public ushort BuckPhaseShift {
            get {
                return ((ushort)(this["BuckPhaseShift"]));
            }
            set {
                this["BuckPhaseShift"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public ushort LMMdutyCycle {
            get {
                return ((ushort)(this["LMMdutyCycle"]));
            }
            set {
                this["LMMdutyCycle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool checkBoxPhase {
            get {
                return ((bool)(this["checkBoxPhase"]));
            }
            set {
                this["checkBoxPhase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte comboBox66XDevices {
            get {
                return ((byte)(this["comboBox66XDevices"]));
            }
            set {
                this["comboBox66XDevices"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool checkBoxAllChannel {
            get {
                return ((bool)(this["checkBoxAllChannel"]));
            }
            set {
                this["checkBoxAllChannel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte comboBoxSort {
            get {
                return ((byte)(this["comboBoxSort"]));
            }
            set {
                this["comboBoxSort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public int comboBoxCMWTAP {
            get {
                return ((int)(this["comboBoxCMWTAP"]));
            }
            set {
                this["comboBoxCMWTAP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"\"")]
        public string currentlySelectedRegister {
            get {
                return ((string)(this["currentlySelectedRegister"]));
            }
            set {
                this["currentlySelectedRegister"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"\"")]
        public string autoLoadFileName {
            get {
                return ((string)(this["autoLoadFileName"]));
            }
            set {
                this["autoLoadFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool checkBoxAutoLoadFile {
            get {
                return ((bool)(this["checkBoxAutoLoadFile"]));
            }
            set {
                this["checkBoxAutoLoadFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte comboBoxBusWalkDevices {
            get {
                return ((byte)(this["comboBoxBusWalkDevices"]));
            }
            set {
                this["comboBoxBusWalkDevices"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int mtpConfigModes {
            get {
                return ((int)(this["mtpConfigModes"]));
            }
            set {
                this["mtpConfigModes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"\"")]
        public string currentlySelectedRegisterMTP_0_1_4_5 {
            get {
                return ((string)(this["currentlySelectedRegisterMTP_0_1_4_5"]));
            }
            set {
                this["currentlySelectedRegisterMTP_0_1_4_5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"\"")]
        public string currentlySelectedRegisterMTP_2_6 {
            get {
                return ((string)(this["currentlySelectedRegisterMTP_2_6"]));
            }
            set {
                this["currentlySelectedRegisterMTP_2_6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"\"")]
        public string currentlySelectedRegisterMTP_3_7 {
            get {
                return ((string)(this["currentlySelectedRegisterMTP_3_7"]));
            }
            set {
                this["currentlySelectedRegisterMTP_3_7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"\"")]
        public string currentlySelectedRegisterMTP_8_9 {
            get {
                return ((string)(this["currentlySelectedRegisterMTP_8_9"]));
            }
            set {
                this["currentlySelectedRegisterMTP_8_9"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"\"")]
        public string currentlySelectedRegisterMTP_10 {
            get {
                return ((string)(this["currentlySelectedRegisterMTP_10"]));
            }
            set {
                this["currentlySelectedRegisterMTP_10"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"\"")]
        public string currentlySelectedRegisterMTP_11 {
            get {
                return ((string)(this["currentlySelectedRegisterMTP_11"]));
            }
            set {
                this["currentlySelectedRegisterMTP_11"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"\"")]
        public string currentlySelectedRegisterMTP_12_13 {
            get {
                return ((string)(this["currentlySelectedRegisterMTP_12_13"]));
            }
            set {
                this["currentlySelectedRegisterMTP_12_13"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"\"")]
        public string currentlySelectedRegisterMTP_14 {
            get {
                return ((string)(this["currentlySelectedRegisterMTP_14"]));
            }
            set {
                this["currentlySelectedRegisterMTP_14"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"\"")]
        public string currentlySelectedRegisterMTP_15 {
            get {
                return ((string)(this["currentlySelectedRegisterMTP_15"]));
            }
            set {
                this["currentlySelectedRegisterMTP_15"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool checkBoxAutoReadAll {
            get {
                return ((bool)(this["checkBoxAutoReadAll"]));
            }
            set {
                this["checkBoxAutoReadAll"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000000")]
        public uint baudRate {
            get {
                return ((uint)(this["baudRate"]));
            }
            set {
                this["baudRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1060.216")]
        public double RegHeight {
            get {
                return ((double)(this["RegHeight"]));
            }
            set {
                this["RegHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1930.678")]
        public double RegWidth {
            get {
                return ((double)(this["RegWidth"]));
            }
            set {
                this["RegWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double RegLeft {
            get {
                return ((double)(this["RegLeft"]));
            }
            set {
                this["RegLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double RegTop {
            get {
                return ((double)(this["RegTop"]));
            }
            set {
                this["RegTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int screensNum {
            get {
                return ((int)(this["screensNum"]));
            }
            set {
                this["screensNum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool checkBoxNoBusWalk {
            get {
                return ((bool)(this["checkBoxNoBusWalk"]));
            }
            set {
                this["checkBoxNoBusWalk"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool checkBoxAckEnable {
            get {
                return ((bool)(this["checkBoxAckEnable"]));
            }
            set {
                this["checkBoxAckEnable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection lmSlider0_1 {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["lmSlider0_1"]));
            }
            set {
                this["lmSlider0_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection lmSlider1_1 {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["lmSlider1_1"]));
            }
            set {
                this["lmSlider1_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection lmSlider2_1 {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["lmSlider2_1"]));
            }
            set {
                this["lmSlider2_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>F</string>
  <string>F</string>
  <string>F</string>
  <string>F</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection lmCheckBox0_1 {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["lmCheckBox0_1"]));
            }
            set {
                this["lmCheckBox0_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>F</string>
  <string>F</string>
  <string>F</string>
  <string>F</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection lmCheckBox1_1 {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["lmCheckBox1_1"]));
            }
            set {
                this["lmCheckBox1_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>F</string>
  <string>F</string>
  <string>F</string>
  <string>F</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection lmCheckBox2_1 {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["lmCheckBox2_1"]));
            }
            set {
                this["lmCheckBox2_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>F</string>
  <string>F</string>
  <string>F</string>
  <string>F</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection lmCheckBox3_1 {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["lmCheckBox3_1"]));
            }
            set {
                this["lmCheckBox3_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>F</string>
  <string>F</string>
  <string>F</string>
  <string>F</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection lmCheckBox4_1 {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["lmCheckBox4_1"]));
            }
            set {
                this["lmCheckBox4_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection lmCombo0 {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["lmCombo0"]));
            }
            set {
                this["lmCombo0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>F</string>
  <string>F</string>
  <string>F</string>
  <string>F</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection lmCheckBox0 {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["lmCheckBox0"]));
            }
            set {
                this["lmCheckBox0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection lmSlider0_2 {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["lmSlider0_2"]));
            }
            set {
                this["lmSlider0_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection lmSlider1_2 {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["lmSlider1_2"]));
            }
            set {
                this["lmSlider1_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection lmSlider2_2 {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["lmSlider2_2"]));
            }
            set {
                this["lmSlider2_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>F</string>
  <string>F</string>
  <string>F</string>
  <string>F</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection lmCheckBox0_2 {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["lmCheckBox0_2"]));
            }
            set {
                this["lmCheckBox0_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>F</string>
  <string>F</string>
  <string>F</string>
  <string>F</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection lmCheckBox1_2 {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["lmCheckBox1_2"]));
            }
            set {
                this["lmCheckBox1_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>F</string>
  <string>F</string>
  <string>F</string>
  <string>F</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection lmCheckBox2_2 {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["lmCheckBox2_2"]));
            }
            set {
                this["lmCheckBox2_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>F</string>
  <string>F</string>
  <string>F</string>
  <string>F</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection lmCheckBox3_2 {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["lmCheckBox3_2"]));
            }
            set {
                this["lmCheckBox3_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>F</string>
  <string>F</string>
  <string>F</string>
  <string>F</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection lmCheckBox4_2 {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["lmCheckBox4_2"]));
            }
            set {
                this["lmCheckBox4_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>F</string>
  <string>F</string>
  <string>F</string>
  <string>F</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection lmCheckBox5_1 {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["lmCheckBox5_1"]));
            }
            set {
                this["lmCheckBox5_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>F</string>
  <string>F</string>
  <string>F</string>
  <string>F</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection lmCheckBox5_2 {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["lmCheckBox5_2"]));
            }
            set {
                this["lmCheckBox5_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public string textBoxWriteDelay {
            get {
                return ((string)(this["textBoxWriteDelay"]));
            }
            set {
                this["textBoxWriteDelay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string autoLoadFileName664 {
            get {
                return ((string)(this["autoLoadFileName664"]));
            }
            set {
                this["autoLoadFileName664"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string autoLoadFileName665 {
            get {
                return ((string)(this["autoLoadFileName665"]));
            }
            set {
                this["autoLoadFileName665"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string autoLoadFileName667 {
            get {
                return ((string)(this["autoLoadFileName667"]));
            }
            set {
                this["autoLoadFileName667"] = value;
            }
        }
    }
}
